### ISSUE TITLE
Release Package only adds BMCodeHost to Thingworx

### ISSUE THREAD

**Issue by atondorf** [ptc-iot-sharing/BMCoreUIWidgets#2]
I found this TWX-Extension very interesting and wanted to try some of the features.
Sadly after installation of the Extension Package (Core UI Widgets 2.6 Beta 8), only the three CodeEditors are available as imported Widgets. All others (e.g.: BMView) are not.

**Comment by BogdanMihaiciuc** [comment]
The most likely cause is that in addition to this package you are also using some other widget from this github that is using the typescript support library. We recently had to update that library because it was broken when running in Thingworx 9 but it is no longer compatible with the previous release - so now you can run into conflict issues when you install multiple widgets with different versions of the support library.

There are a few fixes you can try:

- If you have not yet upgraded to Thingworx 9, just install the [previous release](https://github.com/ptc-iot-sharing/BMCoreUIWidgets/releases/tag/2.6.0-beta.7). The only difference between the latest two releases is Thingworx 9 compatibility
 - Check the other widgets that you have from here and ensure they are up to date.

**Comment by atondorf** [comment]
I tried it on a fresh TWX-9.0 ... only extension installed is JavaBased AutoAuth.
Do I need to install TYpeScript support library separately?

**Comment by BogdanMihaiciuc** [comment]
No, I will look into it. It should work on a fresh install.

**Comment by BogdanMihaiciuc** [comment]
Do you get any kind of error message in the browser console when you open the composer or the mashup builder?

**Comment by atondorf** [comment]
I can not open the components in the mashup builder ... they are not included in the widget List:
Only CodeEditors available ... and the Console does not show any Error. Only some warnings regarding missing translations.
E.G:: WARN: i18n translation is missing for the string tw.confirmation-ide.ptcs-properties.second-button-tooltip-field.description

![Mashup-Widgets](https://user-images.githubusercontent.com/13481582/92222770-c9bc6800-ee9f-11ea-98b7-5e92f3cb6bb7.png)
![Installed_Ext](https://user-images.githubusercontent.com/13481582/92222772-ca54fe80-ee9f-11ea-8da1-6d6b52dfe6be.png)

**Comment by BogdanMihaiciuc** [comment]
Note that the other widgets do not appear in the “imported” category. They should appear under “All”

**Comment by atondorf** [comment]
Ahh ... ok. Found them ... just looked at the wrong position.
Thanks a lot for your help.
